name: osl-action-spotting
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit
  - pip
  - pip:
    - SoccerNet
    - matplotlib
    - scikit-learn
    - pytorch-lightning
    - opencv-python
    - moviepy
    - tqdm
    - tabulate
    - timm
    - mmengine
    - numpy
    - mmengine
    - torch